# ===================================
#  Relation Behavior Config
# ===================================

genres:
    label: Genres
    view:
        list: $/fw/backend/models/genre/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        form: $/fw/backend/models/genre/fields.yaml
        recordsPerPage: 10

persons:
    label: Person
    view:
        list: $/fw/backend/models/person/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        form: $/fw/backend/models/person/fields.yaml
        recordsPerPage: 10

organisations:
    label: Organisations
    view:
        list: $/fw/backend/models/organisation/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        form: $/fw/backend/models/organisation/fields.yaml
        recordsPerPage: 10
