# ===================================
#  Relation Behavior Config
# ===================================

genres:
    label: Genres
    view:
        list: $/fw/backend/models/genre/columns.yaml
        toolbarButtons: create|update|delete
    manage:
        form: $/fw/backend/models/genre/fields.yaml
        recordsPerPage: 10