metasettings:
    label: Метавселенные
    view:
        list:  ~/plugins/fw/backend/models/universe/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        form:  ~/plugins/fw/backend/models/universe/fields.yaml
        list:  ~/plugins/fw/backend/models/universe/columns.yaml
        recordsPerPage: 10
        showSearch: true
