plugin:
    name: 'fw.backend::lang.plugin.name'
    description: 'fun-wiki backend'
    author: fun-wiki
    icon: oc-icon-database
    iconSvg: plugins/fw/backend/assets/images/plugin-logo.svg
    homepage: ''
navigation:
    fw-menu:
        label: Энциклопедия
        url: fw/backend/universe
        icon: icon-adn
        iconSvg: plugins/fw/backend/assets/images/plugin-logo.svg
        sideMenu:
            universes:
                label: Вселенные
                url: fw/backend/universe
                iconSvg: plugins/fw/backend/assets/images/universes.svg
            person:
                label: Люди
                url: fw/backend/person
                iconSvg: plugins/fw/backend/assets/images/persons.svg
            organistions:
                label: Организации
                url: fw/backend/organisations
                icon: icon-sitemap
            book:
                label: Книги
                url: fw/backend/book
                icon: icon-book
    fw-menu-add:
        label: Справочники
        url: fw/backend/genre
        icon: icon-database
        sideMenu:
            genres:
                label: Жанры
                url: fw/backend/genre
                icon: icon-sitemap
            PersonRoles:
                label: 'Person Roles'
                url: fw/backend/personroles
                icon: icon-sitemap
            literature_type:
                label: 'Вид произведения'
                url: fw/backend/literaturetype
                icon: icon-book
            book-series:
                label: 'Книжные серии'
                url: fw/backend/bookseries
                icon: icon-book
