plugin:
    name: F.UN - Энциклопедия фантастических вселенных
    description: fun-wiki backend
    author: CRYDEsigN
    icon: oc-icon-bookmark-o
    iconSvg: plugins/fw/backend/assets/images/plugin-logo.svg
    homepage: https://fun-wiki.ru
navigation:
    fw-menu:
        label: Энциклопедия
        url: fw/backend/dashboard
        icon: icon-adn
        iconSvg: plugins/fw/backend/assets/images/plugin-logo.svg
        sideMenu:
            logo:
                label: fun
                url: fw/backend/dashboard
                iconSvg: plugins/fw/backend/assets/images/plugin-logo.svg
            news:
                label: Новости
                url: fw/backend/news
                iconSvg: plugins/fw/backend/assets/images/news.svg
            universes:
                label: Вселенные
                url: fw/backend/universe
                iconSvg: plugins/fw/backend/assets/images/universe.svg
            person:
                label: Люди
                url: fw/backend/person
                iconSvg: plugins/fw/backend/assets/images/person.svg
            organistions:
                label: Компании
                url: fw/backend/company
                iconSvg: plugins/fw/backend/assets/images/company.svg
            book-editions:
                label: Книги
                url: fw/backend/book
                iconSvg: plugins/fw/backend/assets/images/book.svg
            videogame:
                label: Видеоигры
                url: fw/backend/videogame
                iconSvg: plugins/fw/backend/assets/images/videogame.svg
    fw-menu-add:
        label: Справочники
        url: fw/backend/genre
        icon: icon-database
        sideMenu:
            genres:
                label: Жанры
                url: fw/backend/genre
                icon: icon-sitemap
            personRoles:
                label: Person Roles
                url: fw/backend/personroles
                icon: icon-sitemap
            platform:
                label: Игровые платформы
                url: fw/backend/platform
                icon: icon-windows
            game-types:
                label: Игровые жанры
                url: fw/backend/gametype
                icon: icon-gamepad
    content:
        label: Контент
        url: fw/backend/content
        icon: icon-archive
        sideMenu:
            test:
                label: test
                url: fw/backend/test
                icon: icon-sitemap
    category:
        label: Каталог
        url: fw/backend/category
        icon: icon-sitemap
