plugin:
    name: 'fw.backend::lang.plugin.name'
    description: 'fun-wiki backend'
    author: fun-wiki
    icon: oc-icon-database
    homepage: ''
navigation:
    fw-menu:
        label: Энциклопедия
        url: fw/backend/universe
        icon: icon-adn
        sideMenu:
            universes:
                label: Вселенные
                url: fw/backend/universe
                icon: icon-sitemap
            person:
                label: Люди
                url: fw/backend/person
                icon: icon-sitemap
    main-menu-item2:
        label: Справочники
        url: fw/backend/genre
        icon: icon-database
        sideMenu:
            genres:
                label: Жанры
                url: fw/backend/genre
                icon: icon-sitemap
