list: $/fw/backend/models/platform/columns.yaml
modelClass: fw\Backend\Models\Platform
title: Platform
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/platform/update/:id'
