list: $/fw/backend/models/company/columns.yaml
modelClass: fw\Backend\Models\Company
title: Organisations
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/company/update/:id'
