list: $/fw/backend/models/organisation/columns.yaml
modelClass: fw\Backend\Models\Organisation
title: Organisations
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/organisations/update/:id'
