name: Организация
form: $/fw/backend/models/company/fields.yaml
modelClass: fw\Backend\Models\Company
defaultRedirect: fw/backend/company
create:
    redirect: 'fw/backend/company/update/:id'
    redirectClose: fw/backend/company
update:
    redirect: fw/backend/company
    redirectClose: fw/backend/company
