list: $/fw/backend/models/literaturetype/columns.yaml
modelClass: fw\Backend\Models\LiteratureType
title: LiteratureType
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/literaturetype/update/:id'
