# ===================================
#  Relation Behavior Config
# ===================================

book_content:
    label: Содержание
    view:
        list:  ~/plugins/fw/backend/models/book/fields/book_content/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        form:  ~/plugins/fw/backend/models/book/fields/book_content/fields.yaml
        list:  ~/plugins/fw/backend/models/book/fields/book_content/columns.yaml
        showSearch: true

book_editions:
    label: Издания
    view:
        list:  ~/plugins/fw/backend/models/book/fields/book_editions/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        form:  ~/plugins/fw/backend/models/book/fields/book_editions/fields.yaml
        list:  ~/plugins/fw/backend/models/book/fields/book_editions/columns.yaml
        showSearch: true