list: $/fw/backend/models/book/columns.yaml
modelClass: fw\Backend\Models\Book
title: Произведения
noRecordsMessage: 'backend::lang.list.no_records'
showCheckboxes: true
recordsPerPage: 10
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/book/update/:id?type=:post_type'
filter: config_filter.yaml
