# ===================================
#  Relation Behavior Config
# ===================================

authors:
    label: Авторы
    view:
        list: $/fw/backend/models/person/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        form: $/fw/backend/models/person/fields.yaml
        list: $/fw/backend/models/person/columns_authors.yaml
