list: $/fw/backend/models/work/columns.yaml
modelClass: fw\Backend\Models\Work
title: Произведения
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/work/update/:id'
