# ===================================
#  Relation Behavior Config
# ===================================

authors:
    label:
    view:
        list: $/fw/backend/models/person/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        form: $/fw/backend/models/person/fields.yaml
        recordsPerPage: 10

universes:
    label:
    view:
        list: $/fw/backend/models/universe/columns.yaml
        toolbarButtons: add
    manage:
        form: $/fw/backend/models/universe/fields.yaml
        recordsPerPage: 10