list: $/fw/backend/models/content/columns.yaml
modelClass: fw\Backend\Models\Content
title: Content
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/content/update/:id'
