list: $/fw/backend/models/permalink/columns.yaml
modelClass: fw\Backend\Models\Permalink
title: Permalink
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/permalink/update/:id'
