list: $/fw/backend/models/personrole/columns.yaml
modelClass: fw\Backend\Models\PersonRole
title: PersonRoles
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/personroles/update/:id'
