list: $/fw/backend/models/videogame/columns.yaml
modelClass: fw\Backend\Models\Videogame
title: Videogame
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/videogame/update/:id'
