list: $/fw/backend/models/genre/columns.yaml
modelClass: fw\Backend\Models\Genre
title: Genre
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/genre/update/:id'
