name: Content
form: $/fw/backend/models/article/fields.yaml
modelClass: fw\Backend\Models\Article
defaultRedirect: fw/backend/article
create:
    redirect: 'fw/backend/article/update/:id'
    redirectClose: fw/backend/article
update:
    redirect: fw/backend/article
    redirectClose: fw/backend/article
