title: Контент
list: $/fw/backend/models/content/columns.yaml
modelClass: fw\Backend\Models\Content
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
recordUrl: 'fw/backend/:contentable_type/update/:contentable_id'
toolbar:
    buttons: list_toolbar
