title: News
modelClass: \fw\Backend\Models\News
list: $/fw/backend/models/news/columns.yaml
recordUrl: 'fw/backend/news/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
