# ===================================
#  Relation Behavior Config
# ===================================

pseudos:
    label: Люди
    view:
        list:  ~/plugins/fw/backend/models/person/columns_authors.yaml
        toolbarButtons: create|add|remove
    manage:
        form:  ~/plugins/fw/backend/models/person/fields.yaml
        list:  ~/plugins/fw/backend/models/person/columns_authors.yaml
        scope: nopseudo
        showSearch: true
        recordsPerPage: 10

genres:
    label: Жанры
    view:
        list:  ~/plugins/fw/backend/models/genre/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        form:  ~/plugins/fw/backend/models/genre/fields.yaml
        recordsPerPage: 10
