list: $/fw/backend/models/person/columns_authors.yaml
modelClass: fw\Backend\Models\Person
title: Авторы
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: false
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/person/update/:id'
