name: BookSeries
form: $/fw/backend/models/bookseries/fields.yaml
modelClass: fw\Backend\Models\BookSeries
defaultRedirect: fw/backend/bookseries
create:
    redirect: 'fw/backend/bookseries/update/:id'
    redirectClose: fw/backend/bookseries
update:
    redirect: fw/backend/bookseries
    redirectClose: fw/backend/bookseries
