list: $/fw/backend/models/bookseries/columns.yaml
modelClass: fw\Backend\Models\BookSeries
title: BookSeries
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/bookseries/update/:id'
