list: $/fw/backend/models/bookedition/columns.yaml
modelClass: fw\Backend\Models\BookEdition
title: BookEdition
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/bookedition/update/:id'
