name: Pseudo
form: $/fw/backend/models/pseudo/fields.yaml
modelClass: fw\Backend\Models\Pseudo
defaultRedirect: fw/backend/pseudo
create:
    redirect: 'fw/backend/pseudo/update/:id'
    redirectClose: fw/backend/pseudo
update:
    redirect: fw/backend/pseudo
    redirectClose: fw/backend/pseudo
