list: $/fw/backend/models/pseudo/columns.yaml
modelClass: fw\Backend\Models\Pseudo
title: Pseudo
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'fw/backend/pseudo/update/:id'
